//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.1433.
// 
#pragma warning disable 1591

namespace CryptoEditor.CryptoEditorServiceBackup {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BackupServiceSoap", Namespace="http://cryptoeditor.com/")]
    public partial class BackupService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback IsLicenseValidOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEncryptedLicenseOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateKeyOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConfirmOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegisterOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoadOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BackupService() {
            this.Url = global::CryptoEditor.Properties.Settings.Default.CryptoEditor_CryptoEditorServiceBackup_BackupService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event IsLicenseValidCompletedEventHandler IsLicenseValidCompleted;
        
        /// <remarks/>
        public event GetEncryptedLicenseCompletedEventHandler GetEncryptedLicenseCompleted;
        
        /// <remarks/>
        public event UpdateKeyCompletedEventHandler UpdateKeyCompleted;
        
        /// <remarks/>
        public event ConfirmCompletedEventHandler ConfirmCompleted;
        
        /// <remarks/>
        public event RegisterCompletedEventHandler RegisterCompleted;
        
        /// <remarks/>
        public event SaveCompletedEventHandler SaveCompleted;
        
        /// <remarks/>
        public event LoadCompletedEventHandler LoadCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cryptoeditor.com/IsLicenseValid", RequestNamespace="http://cryptoeditor.com/", ResponseNamespace="http://cryptoeditor.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CryptoEditorServiceCodes IsLicenseValid(string email, string userLicense) {
            object[] results = this.Invoke("IsLicenseValid", new object[] {
                        email,
                        userLicense});
            return ((CryptoEditorServiceCodes)(results[0]));
        }
        
        /// <remarks/>
        public void IsLicenseValidAsync(string email, string userLicense) {
            this.IsLicenseValidAsync(email, userLicense, null);
        }
        
        /// <remarks/>
        public void IsLicenseValidAsync(string email, string userLicense, object userState) {
            if ((this.IsLicenseValidOperationCompleted == null)) {
                this.IsLicenseValidOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsLicenseValidOperationCompleted);
            }
            this.InvokeAsync("IsLicenseValid", new object[] {
                        email,
                        userLicense}, this.IsLicenseValidOperationCompleted, userState);
        }
        
        private void OnIsLicenseValidOperationCompleted(object arg) {
            if ((this.IsLicenseValidCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsLicenseValidCompleted(this, new IsLicenseValidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cryptoeditor.com/GetEncryptedLicense", RequestNamespace="http://cryptoeditor.com/", ResponseNamespace="http://cryptoeditor.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetEncryptedLicense(string email) {
            object[] results = this.Invoke("GetEncryptedLicense", new object[] {
                        email});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetEncryptedLicenseAsync(string email) {
            this.GetEncryptedLicenseAsync(email, null);
        }
        
        /// <remarks/>
        public void GetEncryptedLicenseAsync(string email, object userState) {
            if ((this.GetEncryptedLicenseOperationCompleted == null)) {
                this.GetEncryptedLicenseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEncryptedLicenseOperationCompleted);
            }
            this.InvokeAsync("GetEncryptedLicense", new object[] {
                        email}, this.GetEncryptedLicenseOperationCompleted, userState);
        }
        
        private void OnGetEncryptedLicenseOperationCompleted(object arg) {
            if ((this.GetEncryptedLicenseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEncryptedLicenseCompleted(this, new GetEncryptedLicenseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cryptoeditor.com/UpdateKey", RequestNamespace="http://cryptoeditor.com/", ResponseNamespace="http://cryptoeditor.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CryptoEditorServiceCodes UpdateKey(string email, string license, string encryptedLicense) {
            object[] results = this.Invoke("UpdateKey", new object[] {
                        email,
                        license,
                        encryptedLicense});
            return ((CryptoEditorServiceCodes)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateKeyAsync(string email, string license, string encryptedLicense) {
            this.UpdateKeyAsync(email, license, encryptedLicense, null);
        }
        
        /// <remarks/>
        public void UpdateKeyAsync(string email, string license, string encryptedLicense, object userState) {
            if ((this.UpdateKeyOperationCompleted == null)) {
                this.UpdateKeyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateKeyOperationCompleted);
            }
            this.InvokeAsync("UpdateKey", new object[] {
                        email,
                        license,
                        encryptedLicense}, this.UpdateKeyOperationCompleted, userState);
        }
        
        private void OnUpdateKeyOperationCompleted(object arg) {
            if ((this.UpdateKeyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateKeyCompleted(this, new UpdateKeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cryptoeditor.com/Confirm", RequestNamespace="http://cryptoeditor.com/", ResponseNamespace="http://cryptoeditor.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CryptoEditorServiceCodes Confirm(string email, string license, string encryptedLicense) {
            object[] results = this.Invoke("Confirm", new object[] {
                        email,
                        license,
                        encryptedLicense});
            return ((CryptoEditorServiceCodes)(results[0]));
        }
        
        /// <remarks/>
        public void ConfirmAsync(string email, string license, string encryptedLicense) {
            this.ConfirmAsync(email, license, encryptedLicense, null);
        }
        
        /// <remarks/>
        public void ConfirmAsync(string email, string license, string encryptedLicense, object userState) {
            if ((this.ConfirmOperationCompleted == null)) {
                this.ConfirmOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConfirmOperationCompleted);
            }
            this.InvokeAsync("Confirm", new object[] {
                        email,
                        license,
                        encryptedLicense}, this.ConfirmOperationCompleted, userState);
        }
        
        private void OnConfirmOperationCompleted(object arg) {
            if ((this.ConfirmCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConfirmCompleted(this, new ConfirmCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cryptoeditor.com/Register", RequestNamespace="http://cryptoeditor.com/", ResponseNamespace="http://cryptoeditor.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CryptoEditorServiceCodes Register(string email, string profile, string fullName) {
            object[] results = this.Invoke("Register", new object[] {
                        email,
                        profile,
                        fullName});
            return ((CryptoEditorServiceCodes)(results[0]));
        }
        
        /// <remarks/>
        public void RegisterAsync(string email, string profile, string fullName) {
            this.RegisterAsync(email, profile, fullName, null);
        }
        
        /// <remarks/>
        public void RegisterAsync(string email, string profile, string fullName, object userState) {
            if ((this.RegisterOperationCompleted == null)) {
                this.RegisterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegisterOperationCompleted);
            }
            this.InvokeAsync("Register", new object[] {
                        email,
                        profile,
                        fullName}, this.RegisterOperationCompleted, userState);
        }
        
        private void OnRegisterOperationCompleted(object arg) {
            if ((this.RegisterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegisterCompleted(this, new RegisterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cryptoeditor.com/Save", RequestNamespace="http://cryptoeditor.com/", ResponseNamespace="http://cryptoeditor.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CryptoEditorServiceCodes Save(string email, string license, string plugin, string xml) {
            object[] results = this.Invoke("Save", new object[] {
                        email,
                        license,
                        plugin,
                        xml});
            return ((CryptoEditorServiceCodes)(results[0]));
        }
        
        /// <remarks/>
        public void SaveAsync(string email, string license, string plugin, string xml) {
            this.SaveAsync(email, license, plugin, xml, null);
        }
        
        /// <remarks/>
        public void SaveAsync(string email, string license, string plugin, string xml, object userState) {
            if ((this.SaveOperationCompleted == null)) {
                this.SaveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveOperationCompleted);
            }
            this.InvokeAsync("Save", new object[] {
                        email,
                        license,
                        plugin,
                        xml}, this.SaveOperationCompleted, userState);
        }
        
        private void OnSaveOperationCompleted(object arg) {
            if ((this.SaveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveCompleted(this, new SaveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cryptoeditor.com/Load", RequestNamespace="http://cryptoeditor.com/", ResponseNamespace="http://cryptoeditor.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Load(string email, string license, string plugin) {
            object[] results = this.Invoke("Load", new object[] {
                        email,
                        license,
                        plugin});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LoadAsync(string email, string license, string plugin) {
            this.LoadAsync(email, license, plugin, null);
        }
        
        /// <remarks/>
        public void LoadAsync(string email, string license, string plugin, object userState) {
            if ((this.LoadOperationCompleted == null)) {
                this.LoadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoadOperationCompleted);
            }
            this.InvokeAsync("Load", new object[] {
                        email,
                        license,
                        plugin}, this.LoadOperationCompleted, userState);
        }
        
        private void OnLoadOperationCompleted(object arg) {
            if ((this.LoadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoadCompleted(this, new LoadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cryptoeditor.com/")]
    public enum CryptoEditorServiceCodes {
        
        /// <remarks/>
        SUCCESS,
        
        /// <remarks/>
        USER_EXIST,
        
        /// <remarks/>
        USER_DOES_NOT_EXIST,
        
        /// <remarks/>
        USER_DISABLED,
        
        /// <remarks/>
        USER_EXPIRED,
        
        /// <remarks/>
        INVALID_LICENSE,
        
        /// <remarks/>
        SYSTEM_ERROR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void IsLicenseValidCompletedEventHandler(object sender, IsLicenseValidCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsLicenseValidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsLicenseValidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CryptoEditorServiceCodes Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CryptoEditorServiceCodes)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void GetEncryptedLicenseCompletedEventHandler(object sender, GetEncryptedLicenseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEncryptedLicenseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEncryptedLicenseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void UpdateKeyCompletedEventHandler(object sender, UpdateKeyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateKeyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateKeyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CryptoEditorServiceCodes Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CryptoEditorServiceCodes)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void ConfirmCompletedEventHandler(object sender, ConfirmCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConfirmCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConfirmCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CryptoEditorServiceCodes Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CryptoEditorServiceCodes)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void RegisterCompletedEventHandler(object sender, RegisterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegisterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegisterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CryptoEditorServiceCodes Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CryptoEditorServiceCodes)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void SaveCompletedEventHandler(object sender, SaveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CryptoEditorServiceCodes Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CryptoEditorServiceCodes)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void LoadCompletedEventHandler(object sender, LoadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591